org:
  org_id: "TEST"
app: 
  app_home: "{{.vars.app.app_home}}"
  home: "{{.env.HOME}}"

log:
  level: debug
  file: "{{.vars.app.app_home}}/logs/app.log"
  loggers:
    chat: 
      level: trace
    llm: 
      level: trace
    bot: 
      level: debug
    extract: 
      level: debug
    database: 
      level: debug
    vec_store: 
      level: debug
    cache: 
      level: debug
    kb: 
      level: trace

web:
  certs:
    - name: "server"
      cert: "{{.vars.app.app_home}}/ssl/server.crt"
      cert_key: "{{.vars.app.app_home}}/ssl/server.key"
      ca: "{{.vars.app.app_home}}/ssl/ca.crt"
    - name: "ca"
      cert: "{{.vars.app.app_home}}/ssl/ca.crt"
       
  servers:
    - name: "public"
      listen: "0.0.0.0:9988"
      static_dir: "{{.vars.app.app_home}}/static"
      error_log: "{{.vars.app.app_home}}/logs/http_error.log"
      access_log: "{{.vars.app.app_home}}/logs/http_access.log"
      endpoints:
        - path: "/api/v1"
          module: "actions"
          group: "sapi"